---
output:
  govdown::govdown_document:
    page_title: "CO C&C Session: Make an R package the easy way"
---

## Make an R package the easy way

::: {.lead-para}
You use R packages all the time. You may have heard that developing your own packages is an important R skill. But how do you do it? It looks confusing. This talk will contain slides to introduce the concepts and a live demo to show how to build a package from scratch.
:::

Table: Session details

| | |
|--:|--|
| Date | 01 November 2019 |
| Presenter | Matt Dray |
| Abstract | R packages: when should you make one and how do you do it? Matt Dray will live-build a minimal package with {usethis}, a package that greatly simplifies the process. |
| Type | Methods demo |
| Level | 0: No experience necessary |

#### Materials

You'll be able to access these after the session:

* the [slides](https://matt-dray.github.io/r-pkg-slides/) and their [source](https://github.com/matt-dray/r-pkg-slides)
* the [demo package](https://github.com/matt-dray/cabinet) that was created in the session

#### Links

Some important links are to:

* the packages [{usethis}](https://usethis.r-lib.org/) and [{devtools}](https://devtools.r-lib.org/)
* [Hilary Parker's 'writing an R package from scratch' post](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) (beginner)
* [Tomas Westlake's update to Hilary's post](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/) (beginner)
* [Karl Broman's R Package Primer site](https://kbroman.org/pkg_primer/) (intermediate)
* [Hadley Wickham's R Packages book](http://r-pkgs.had.co.nz/) (intermediate/advanced)
